// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AgentService is an autogenerated mock type for the AgentService type
type AgentService struct {
	mock.Mock
}

// CreateAgentTask provides a mock function with given fields: c
func (_m *AgentService) CreateAgentTask(c *gin.Context) {
	_m.Called(c)
}

// GetAgentTask provides a mock function with given fields: c
func (_m *AgentService) GetAgentTask(c *gin.Context) {
	_m.Called(c)
}

// HandleChat provides a mock function with given fields: c
func (_m *AgentService) HandleChat(c *gin.Context) {
	_m.Called(c)
}

// ListSkills provides a mock function with given fields: c
func (_m *AgentService) ListSkills(c *gin.Context) {
	_m.Called(c)
}

// SearchSkills provides a mock function with given fields: c
func (_m *AgentService) SearchSkills(c *gin.Context) {
	_m.Called(c)
}

// NewAgentService creates a new instance of AgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentService {
	mock := &AgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
