// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ToolLister is an autogenerated mock type for the ToolLister type
type ToolLister struct {
	mock.Mock
}

// List provides a mock function with no fields
func (_m *ToolLister) List() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewToolLister creates a new instance of ToolLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolLister {
	mock := &ToolLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
