// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	io "io"

	domainknowledge "github.com/luoxiaojun1992/data-agent/internal/domain/knowledge"

	mock "github.com/stretchr/testify/mock"
)

// KnowledgeService is an autogenerated mock type for the KnowledgeService type
type KnowledgeService struct {
	mock.Mock
}

// AddChunks provides a mock function with given fields: docID, texts
func (_m *KnowledgeService) AddChunks(docID string, texts []string) error {
	ret := _m.Called(docID, texts)

	if len(ret) == 0 {
		panic("no return value specified for AddChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(docID, texts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDoc provides a mock function with given fields: userID, title, fileName, fileType, sizeBytes, gridFSFileID
func (_m *KnowledgeService) CreateDoc(userID string, title string, fileName string, fileType string, sizeBytes int64, gridFSFileID string) (*domainknowledge.KnowledgeDoc, error) {
	ret := _m.Called(userID, title, fileName, fileType, sizeBytes, gridFSFileID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDoc")
	}

	var r0 *domainknowledge.KnowledgeDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int64, string) (*domainknowledge.KnowledgeDoc, error)); ok {
		return rf(userID, title, fileName, fileType, sizeBytes, gridFSFileID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int64, string) *domainknowledge.KnowledgeDoc); ok {
		r0 = rf(userID, title, fileName, fileType, sizeBytes, gridFSFileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainknowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int64, string) error); ok {
		r1 = rf(userID, title, fileName, fileType, sizeBytes, gridFSFileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDoc provides a mock function with given fields: id
func (_m *KnowledgeService) DeleteDoc(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDoc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDoc provides a mock function with given fields: id
func (_m *KnowledgeService) GetDoc(id string) (*domainknowledge.KnowledgeDoc, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDoc")
	}

	var r0 *domainknowledge.KnowledgeDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domainknowledge.KnowledgeDoc, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domainknowledge.KnowledgeDoc); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainknowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllDocs provides a mock function with no fields
func (_m *KnowledgeService) ListAllDocs() ([]*domainknowledge.KnowledgeDoc, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAllDocs")
	}

	var r0 []*domainknowledge.KnowledgeDoc
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domainknowledge.KnowledgeDoc, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domainknowledge.KnowledgeDoc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainknowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDocs provides a mock function with given fields: userID
func (_m *KnowledgeService) ListDocs(userID string) ([]*domainknowledge.KnowledgeDoc, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListDocs")
	}

	var r0 []*domainknowledge.KnowledgeDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domainknowledge.KnowledgeDoc, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domainknowledge.KnowledgeDoc); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainknowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: userID, query, topK, role
func (_m *KnowledgeService) Search(userID string, query string, topK int, role string) ([]domainknowledge.SearchResult, error) {
	ret := _m.Called(userID, query, topK, role)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domainknowledge.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int, string) ([]domainknowledge.SearchResult, error)); ok {
		return rf(userID, query, topK, role)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, string) []domainknowledge.SearchResult); ok {
		r0 = rf(userID, query, topK, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domainknowledge.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, string) error); ok {
		r1 = rf(userID, query, topK, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: fileName, contentType, reader
func (_m *KnowledgeService) UploadFile(fileName string, contentType string, reader io.Reader) (string, error) {
	ret := _m.Called(fileName, contentType, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) (string, error)); ok {
		return rf(fileName, contentType, reader)
	}
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) string); ok {
		r0 = rf(fileName, contentType, reader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(fileName, contentType, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKnowledgeService creates a new instance of KnowledgeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKnowledgeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KnowledgeService {
	mock := &KnowledgeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
