// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	io "io"

	domainartifact "github.com/luoxiaojun1992/data-agent/internal/domain/artifact"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Download provides a mock function with given fields: id
func (_m *Service) Download(id string) ([]byte, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadURL provides a mock function with given fields: id
func (_m *Service) DownloadURL(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DownloadURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Service) FindByID(id string) (*domainartifact.Artifact, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domainartifact.Artifact, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domainartifact.Artifact); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBySession provides a mock function with given fields: sessionID
func (_m *Service) ListBySession(sessionID string) ([]*domainartifact.Artifact, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySession")
	}

	var r0 []*domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domainartifact.Artifact, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domainartifact.Artifact); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByTask provides a mock function with given fields: taskID
func (_m *Service) ListByTask(taskID string) ([]*domainartifact.Artifact, error) {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []*domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domainartifact.Artifact, error)); ok {
		return rf(taskID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domainartifact.Artifact); ok {
		r0 = rf(taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: userID, page, pageSize
func (_m *Service) ListByUser(userID string, page int, pageSize int) ([]*domainartifact.Artifact, int64, error) {
	ret := _m.Called(userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*domainartifact.Artifact
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*domainartifact.Artifact, int64, error)); ok {
		return rf(userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*domainartifact.Artifact); ok {
		r0 = rf(userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) int64); ok {
		r1 = rf(userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = rf(userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Upload provides a mock function with given fields: userID, sessionID, taskID, name, mimeType, reader, persistent
func (_m *Service) Upload(userID string, sessionID string, taskID string, name string, mimeType string, reader io.Reader, persistent bool) (*domainartifact.Artifact, error) {
	ret := _m.Called(userID, sessionID, taskID, name, mimeType, reader, persistent)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, io.Reader, bool) (*domainartifact.Artifact, error)); ok {
		return rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, io.Reader, bool) *domainartifact.Artifact); ok {
		r0 = rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string, io.Reader, bool) error); ok {
		r1 = rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
