// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	io "io"

	domainartifact "github.com/luoxiaojun1992/data-agent/internal/domain/artifact"

	mock "github.com/stretchr/testify/mock"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *StorageService) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Download provides a mock function with given fields: id
func (_m *StorageService) Download(id string) ([]byte, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *StorageService) FindByID(id string) (*domainartifact.Artifact, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domainartifact.Artifact, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domainartifact.Artifact); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBySession provides a mock function with given fields: sessionID
func (_m *StorageService) ListBySession(sessionID string) ([]*domainartifact.Artifact, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySession")
	}

	var r0 []*domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domainartifact.Artifact, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domainartifact.Artifact); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByTask provides a mock function with given fields: taskID
func (_m *StorageService) ListByTask(taskID string) ([]*domainartifact.Artifact, error) {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []*domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domainartifact.Artifact, error)); ok {
		return rf(taskID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domainartifact.Artifact); ok {
		r0 = rf(taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: userID, sessionID, taskID, name, mimeType, reader, persistent
func (_m *StorageService) Upload(userID string, sessionID string, taskID string, name string, mimeType string, reader io.Reader, persistent bool) (*domainartifact.Artifact, error) {
	ret := _m.Called(userID, sessionID, taskID, name, mimeType, reader, persistent)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domainartifact.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, io.Reader, bool) (*domainartifact.Artifact, error)); ok {
		return rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, io.Reader, bool) *domainartifact.Artifact); ok {
		r0 = rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainartifact.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string, io.Reader, bool) error); ok {
		r1 = rf(userID, sessionID, taskID, name, mimeType, reader, persistent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
