// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domainapireview "github.com/luoxiaojun1992/data-agent/internal/domain/apireview"
	mock "github.com/stretchr/testify/mock"
)

// APIReviewService is an autogenerated mock type for the APIReviewService type
type APIReviewService struct {
	mock.Mock
}

// Approve provides a mock function with given fields: id, reviewer
func (_m *APIReviewService) Approve(id string, reviewer string) error {
	ret := _m.Called(id, reviewer)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, reviewer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: name, fileName, domain, version, endpoints, rateLimit, submitter
func (_m *APIReviewService) Create(name string, fileName string, domain string, version string, endpoints int, rateLimit int, submitter string) (*domainapireview.APIReview, error) {
	ret := _m.Called(name, fileName, domain, version, endpoints, rateLimit, submitter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domainapireview.APIReview
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int, string) (*domainapireview.APIReview, error)); ok {
		return rf(name, fileName, domain, version, endpoints, rateLimit, submitter)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int, string) *domainapireview.APIReview); ok {
		r0 = rf(name, fileName, domain, version, endpoints, rateLimit, submitter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainapireview.APIReview)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int, int, string) error); ok {
		r1 = rf(name, fileName, domain, version, endpoints, rateLimit, submitter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with no fields
func (_m *APIReviewService) ListAll() ([]domainapireview.APIReview, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domainapireview.APIReview
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domainapireview.APIReview, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domainapireview.APIReview); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domainapireview.APIReview)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reject provides a mock function with given fields: id, reviewer, reason
func (_m *APIReviewService) Reject(id string, reviewer string, reason string) error {
	ret := _m.Called(id, reviewer, reason)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, reviewer, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAPIReviewService creates a new instance of APIReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIReviewService {
	mock := &APIReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
