// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	audit "github.com/luoxiaojun1992/data-agent/internal/service/audit"
	mock "github.com/stretchr/testify/mock"
)

// AuditService is an autogenerated mock type for the AuditService type
type AuditService struct {
	mock.Mock
}

// List provides a mock function with given fields: p
func (_m *AuditService) List(p audit.ListParams) (*audit.ListResult, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *audit.ListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(audit.ListParams) (*audit.ListResult, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(audit.ListParams) *audit.ListResult); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*audit.ListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(audit.ListParams) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuditService creates a new instance of AuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditService {
	mock := &AuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
