// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	task "github.com/luoxiaojun1992/data-agent/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// CancelTask provides a mock function with given fields: id, userID, isSystemAdmin
func (_m *TaskService) CancelTask(id string, userID string, isSystemAdmin bool) error {
	ret := _m.Called(id, userID, isSystemAdmin)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(id, userID, isSystemAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRun provides a mock function with given fields: taskID, userID, isSystemAdmin
func (_m *TaskService) CreateRun(taskID string, userID string, isSystemAdmin bool) (*task.TaskRun, error) {
	ret := _m.Called(taskID, userID, isSystemAdmin)

	if len(ret) == 0 {
		panic("no return value specified for CreateRun")
	}

	var r0 *task.TaskRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (*task.TaskRun, error)); ok {
		return rf(taskID, userID, isSystemAdmin)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) *task.TaskRun); ok {
		r0 = rf(taskID, userID, isSystemAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(taskID, userID, isSystemAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTask provides a mock function with given fields: userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt
func (_m *TaskService) CreateTask(userID string, taskType string, skillChain []string, params map[string]interface{}, modelID string, scheduleMode string, cronExpr string, scheduledAt *time.Time) (*task.Task, *task.TaskRun, error) {
	ret := _m.Called(userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *task.Task
	var r1 *task.TaskRun
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, []string, map[string]interface{}, string, string, string, *time.Time) (*task.Task, *task.TaskRun, error)); ok {
		return rf(userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string, map[string]interface{}, string, string, string, *time.Time) *task.Task); ok {
		r0 = rf(userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, []string, map[string]interface{}, string, string, string, *time.Time) *task.TaskRun); ok {
		r1 = rf(userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, []string, map[string]interface{}, string, string, string, *time.Time) error); ok {
		r2 = rf(userID, taskType, skillChain, params, modelID, scheduleMode, cronExpr, scheduledAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTask provides a mock function with given fields: id, userID, isSystemAdmin
func (_m *TaskService) GetTask(id string, userID string, isSystemAdmin bool) (*task.Task, error) {
	ret := _m.Called(id, userID, isSystemAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (*task.Task, error)); ok {
		return rf(id, userID, isSystemAdmin)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) *task.Task); ok {
		r0 = rf(id, userID, isSystemAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(id, userID, isSystemAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasks provides a mock function with given fields: userID, isSystemAdmin, skip, limit
func (_m *TaskService) ListTasks(userID string, isSystemAdmin bool, skip int64, limit int64) ([]*task.Task, int64, error) {
	ret := _m.Called(userID, isSystemAdmin, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, bool, int64, int64) ([]*task.Task, int64, error)); ok {
		return rf(userID, isSystemAdmin, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(string, bool, int64, int64) []*task.Task); ok {
		r0 = rf(userID, isSystemAdmin, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool, int64, int64) int64); ok {
		r1 = rf(userID, isSystemAdmin, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, bool, int64, int64) error); ok {
		r2 = rf(userID, isSystemAdmin, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetScheduledEnabled provides a mock function with given fields: taskID, userID, isSystemAdmin, enabled
func (_m *TaskService) SetScheduledEnabled(taskID string, userID string, isSystemAdmin bool, enabled bool) error {
	ret := _m.Called(taskID, userID, isSystemAdmin, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetScheduledEnabled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool, bool) error); ok {
		r0 = rf(taskID, userID, isSystemAdmin, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
