// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	task "github.com/luoxiaojun1992/data-agent/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// TaskRunService is an autogenerated mock type for the TaskRunService type
type TaskRunService struct {
	mock.Mock
}

// CancelRun provides a mock function with given fields: id
func (_m *TaskRunService) CancelRun(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CancelRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRun provides a mock function with given fields: id
func (_m *TaskRunService) GetRun(id string) (*task.TaskRun, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRun")
	}

	var r0 *task.TaskRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*task.TaskRun, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *task.TaskRun); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRuns provides a mock function with given fields: taskID, status, skip, limit
func (_m *TaskRunService) ListRuns(taskID string, status string, skip int64, limit int64) ([]*task.TaskRun, int64, error) {
	ret := _m.Called(taskID, status, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRuns")
	}

	var r0 []*task.TaskRun
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) ([]*task.TaskRun, int64, error)); ok {
		return rf(taskID, status, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) []*task.TaskRun); ok {
		r0 = rf(taskID, status, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, int64) int64); ok {
		r1 = rf(taskID, status, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, int64, int64) error); ok {
		r2 = rf(taskID, status, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateRunError provides a mock function with given fields: id, errMsg
func (_m *TaskRunService) UpdateRunError(id string, errMsg string) error {
	ret := _m.Called(id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunResult provides a mock function with given fields: id, result
func (_m *TaskRunService) UpdateRunResult(id string, result map[string]interface{}) error {
	ret := _m.Called(id, result)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(id, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunSessionID provides a mock function with given fields: id, sessionID
func (_m *TaskRunService) UpdateRunSessionID(id string, sessionID string) error {
	ret := _m.Called(id, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunSessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunStatus provides a mock function with given fields: id, status
func (_m *TaskRunService) UpdateRunStatus(id string, status task.Status) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.Status) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRunService creates a new instance of TaskRunService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRunService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRunService {
	mock := &TaskRunService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
