// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	chat "github.com/luoxiaojun1992/data-agent/internal/domain/chat"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ChatService is an autogenerated mock type for the ChatService type
type ChatService struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, req, userID, role
func (_m *ChatService) Process(ctx context.Context, req chat.ChatRequest, userID string, role string) (*chat.ChatResponse, error) {
	ret := _m.Called(ctx, req, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *chat.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.ChatRequest, string, string) (*chat.ChatResponse, error)); ok {
		return rf(ctx, req, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.ChatRequest, string, string) *chat.ChatResponse); ok {
		r0 = rf(ctx, req, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.ChatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.ChatRequest, string, string) error); ok {
		r1 = rf(ctx, req, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stream provides a mock function with given fields: ctx, req, userID, role, w
func (_m *ChatService) Stream(ctx context.Context, req chat.ChatRequest, userID string, role string, w http.ResponseWriter) error {
	ret := _m.Called(ctx, req, userID, role, w)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.ChatRequest, string, string, http.ResponseWriter) error); ok {
		r0 = rf(ctx, req, userID, role, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChatService creates a new instance of ChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatService {
	mock := &ChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
