// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WorkspaceManager is an autogenerated mock type for the WorkspaceManager type
type WorkspaceManager struct {
	mock.Mock
}

// List provides a mock function with given fields: userID, sessionID
func (_m *WorkspaceManager) List(userID string, sessionID string) ([]string, error) {
	ret := _m.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return rf(userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadFile provides a mock function with given fields: userID, sessionID, filename
func (_m *WorkspaceManager) ReadFile(userID string, sessionID string, filename string) ([]byte, error) {
	ret := _m.Called(userID, sessionID, filename)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return rf(userID, sessionID, filename)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(userID, sessionID, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(userID, sessionID, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteFile provides a mock function with given fields: userID, sessionID, filename, data
func (_m *WorkspaceManager) WriteFile(userID string, sessionID string, filename string, data []byte) error {
	ret := _m.Called(userID, sessionID, filename, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []byte) error); ok {
		r0 = rf(userID, sessionID, filename, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkspaceManager creates a new instance of WorkspaceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceManager {
	mock := &WorkspaceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
