// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AuditRepository is an autogenerated mock type for the AuditRepository type
type AuditRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, filter
func (_m *AuditRepository) Count(ctx context.Context, filter map[string]interface{}) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, log
func (_m *AuditRepository) Create(ctx context.Context, log *model.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, filter, skip, limit
func (_m *AuditRepository) List(ctx context.Context, filter map[string]interface{}, skip int64, limit int64) ([]model.AuditLog, error) {
	ret := _m.Called(ctx, filter, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int64, int64) ([]model.AuditLog, error)); ok {
		return rf(ctx, filter, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int64, int64) []model.AuditLog); ok {
		r0 = rf(ctx, filter, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}, int64, int64) error); ok {
		r1 = rf(ctx, filter, skip, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuditRepository creates a new instance of AuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditRepository {
	mock := &AuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
