// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/luoxiaojun1992/data-agent/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// GraphRepository is an autogenerated mock type for the GraphRepository type
type GraphRepository struct {
	mock.Mock
}

// DeleteByDocID provides a mock function with given fields: ctx, docID
func (_m *GraphRepository) DeleteByDocID(ctx context.Context, docID string) error {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDocID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, docID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChunk provides a mock function with given fields: ctx, chunkID
func (_m *GraphRepository) DeleteChunk(ctx context.Context, chunkID string) error {
	ret := _m.Called(ctx, chunkID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, chunkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureSchema provides a mock function with given fields: ctx
func (_m *GraphRepository) EnsureSchema(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSchema")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRelated provides a mock function with given fields: ctx, chunkID, refs
func (_m *GraphRepository) LinkRelated(ctx context.Context, chunkID string, refs []repository.RelatedRef) error {
	ret := _m.Called(ctx, chunkID, refs)

	if len(ret) == 0 {
		panic("no return value specified for LinkRelated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []repository.RelatedRef) error); ok {
		r0 = rf(ctx, chunkID, refs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryTopN provides a mock function with given fields: ctx, anchorID, topN, filter
func (_m *GraphRepository) QueryTopN(ctx context.Context, anchorID string, topN int, filter repository.GraphFilter) ([]repository.GraphNode, error) {
	ret := _m.Called(ctx, anchorID, topN, filter)

	if len(ret) == 0 {
		panic("no return value specified for QueryTopN")
	}

	var r0 []repository.GraphNode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, repository.GraphFilter) ([]repository.GraphNode, error)); ok {
		return rf(ctx, anchorID, topN, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, repository.GraphFilter) []repository.GraphNode); ok {
		r0 = rf(ctx, anchorID, topN, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.GraphNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, repository.GraphFilter) error); ok {
		r1 = rf(ctx, anchorID, topN, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertChunk provides a mock function with given fields: ctx, c
func (_m *GraphRepository) UpsertChunk(ctx context.Context, c repository.GraphChunk) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for UpsertChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GraphChunk) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGraphRepository creates a new instance of GraphRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraphRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GraphRepository {
	mock := &GraphRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
