// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// InviteRepository is an autogenerated mock type for the InviteRepository type
type InviteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, invite
func (_m *InviteRepository) Create(ctx context.Context, invite *model.Invite) error {
	ret := _m.Called(ctx, invite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Invite) error); ok {
		r0 = rf(ctx, invite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByInviteID provides a mock function with given fields: ctx, inviteID
func (_m *InviteRepository) FindByInviteID(ctx context.Context, inviteID string) (*model.Invite, error) {
	ret := _m.Called(ctx, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for FindByInviteID")
	}

	var r0 *model.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Invite, error)); ok {
		return rf(ctx, inviteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Invite); ok {
		r0 = rf(ctx, inviteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inviteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTokenHash provides a mock function with given fields: ctx, hash
func (_m *InviteRepository) FindByTokenHash(ctx context.Context, hash string) (*model.Invite, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *model.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Invite, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Invite); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, createdBy, skip, limit
func (_m *InviteRepository) List(ctx context.Context, createdBy string, skip int64, limit int64) ([]model.Invite, int64, error) {
	ret := _m.Called(ctx, createdBy, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Invite
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]model.Invite, int64, error)); ok {
		return rf(ctx, createdBy, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []model.Invite); ok {
		r0 = rf(ctx, createdBy, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, createdBy, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, createdBy, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkAccepted provides a mock function with given fields: ctx, inviteID, userID
func (_m *InviteRepository) MarkAccepted(ctx context.Context, inviteID string, userID string) error {
	ret := _m.Called(ctx, inviteID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAccepted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, inviteID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Revoke provides a mock function with given fields: ctx, inviteID
func (_m *InviteRepository) Revoke(ctx context.Context, inviteID string) error {
	ret := _m.Called(ctx, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, inviteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInviteRepository creates a new instance of InviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteRepository {
	mock := &InviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
