// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	knowledge "github.com/luoxiaojun1992/data-agent/internal/domain/knowledge"
	mock "github.com/stretchr/testify/mock"
)

// KBRepository is an autogenerated mock type for the KBRepository type
type KBRepository struct {
	mock.Mock
}

// AddChunks provides a mock function with given fields: ctx, chunks
func (_m *KBRepository) AddChunks(ctx context.Context, chunks []*knowledge.Chunk) error {
	ret := _m.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for AddChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*knowledge.Chunk) error); ok {
		r0 = rf(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDoc provides a mock function with given fields: ctx, doc
func (_m *KBRepository) CreateDoc(ctx context.Context, doc *knowledge.KnowledgeDoc) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for CreateDoc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *knowledge.KnowledgeDoc) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChunks provides a mock function with given fields: ctx, docID
func (_m *KBRepository) DeleteChunks(ctx context.Context, docID string) (int64, error) {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChunks")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, docID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, docID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDoc provides a mock function with given fields: ctx, id
func (_m *KBRepository) DeleteDoc(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDoc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFile provides a mock function with given fields: ctx, fileID
func (_m *KBRepository) DeleteFile(ctx context.Context, fileID string) error {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadFile provides a mock function with given fields: ctx, fileID
func (_m *KBRepository) DownloadFile(ctx context.Context, fileID string) ([]byte, error) {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, fileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDoc provides a mock function with given fields: ctx, id
func (_m *KBRepository) GetDoc(ctx context.Context, id string) (*knowledge.KnowledgeDoc, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDoc")
	}

	var r0 *knowledge.KnowledgeDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*knowledge.KnowledgeDoc, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *knowledge.KnowledgeDoc); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*knowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllDocs provides a mock function with given fields: ctx, skip, limit
func (_m *KBRepository) ListAllDocs(ctx context.Context, skip int64, limit int64) ([]*knowledge.KnowledgeDoc, int64, error) {
	ret := _m.Called(ctx, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListAllDocs")
	}

	var r0 []*knowledge.KnowledgeDoc
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*knowledge.KnowledgeDoc, int64, error)); ok {
		return rf(ctx, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []*knowledge.KnowledgeDoc); ok {
		r0 = rf(ctx, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*knowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) int64); ok {
		r1 = rf(ctx, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = rf(ctx, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListDocs provides a mock function with given fields: ctx, userID, skip, limit
func (_m *KBRepository) ListDocs(ctx context.Context, userID string, skip int64, limit int64) ([]*knowledge.KnowledgeDoc, int64, error) {
	ret := _m.Called(ctx, userID, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDocs")
	}

	var r0 []*knowledge.KnowledgeDoc
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*knowledge.KnowledgeDoc, int64, error)); ok {
		return rf(ctx, userID, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*knowledge.KnowledgeDoc); ok {
		r0 = rf(ctx, userID, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*knowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, userID, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, userID, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListDocsByVisibility provides a mock function with given fields: ctx, userID, isSystemAdmin, q, skip, limit
func (_m *KBRepository) ListDocsByVisibility(ctx context.Context, userID string, isSystemAdmin bool, q string, skip int64, limit int64) ([]*knowledge.KnowledgeDoc, int64, error) {
	ret := _m.Called(ctx, userID, isSystemAdmin, q, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDocsByVisibility")
	}

	var r0 []*knowledge.KnowledgeDoc
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, string, int64, int64) ([]*knowledge.KnowledgeDoc, int64, error)); ok {
		return rf(ctx, userID, isSystemAdmin, q, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, string, int64, int64) []*knowledge.KnowledgeDoc); ok {
		r0 = rf(ctx, userID, isSystemAdmin, q, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*knowledge.KnowledgeDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, string, int64, int64) int64); ok {
		r1 = rf(ctx, userID, isSystemAdmin, q, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, bool, string, int64, int64) error); ok {
		r2 = rf(ctx, userID, isSystemAdmin, q, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SearchChunks provides a mock function with given fields: ctx, query, userID, isSystemAdmin, topK
func (_m *KBRepository) SearchChunks(ctx context.Context, query string, userID string, isSystemAdmin bool, topK int) ([]*knowledge.SearchResult, error) {
	ret := _m.Called(ctx, query, userID, isSystemAdmin, topK)

	if len(ret) == 0 {
		panic("no return value specified for SearchChunks")
	}

	var r0 []*knowledge.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, int) ([]*knowledge.SearchResult, error)); ok {
		return rf(ctx, query, userID, isSystemAdmin, topK)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, int) []*knowledge.SearchResult); ok {
		r0 = rf(ctx, query, userID, isSystemAdmin, topK)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*knowledge.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool, int) error); ok {
		r1 = rf(ctx, query, userID, isSystemAdmin, topK)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPublicFlag provides a mock function with given fields: ctx, id, isPublic
func (_m *KBRepository) SetPublicFlag(ctx context.Context, id string, isPublic bool) error {
	ret := _m.Called(ctx, id, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for SetPublicFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, isPublic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChunkVisibility provides a mock function with given fields: ctx, docID, isPublic
func (_m *KBRepository) UpdateChunkVisibility(ctx context.Context, docID string, isPublic bool) error {
	ret := _m.Called(ctx, docID, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChunkVisibility")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, docID, isPublic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDocStatus provides a mock function with given fields: ctx, id, status, chunkCount, progressPercent
func (_m *KBRepository) UpdateDocStatus(ctx context.Context, id string, status knowledge.DocStatus, chunkCount int, progressPercent int) error {
	ret := _m.Called(ctx, id, status, chunkCount, progressPercent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, knowledge.DocStatus, int, int) error); ok {
		r0 = rf(ctx, id, status, chunkCount, progressPercent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadFile provides a mock function with given fields: ctx, fileID, reader
func (_m *KBRepository) UploadFile(ctx context.Context, fileID string, reader io.Reader) error {
	ret := _m.Called(ctx, fileID, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, fileID, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKBRepository creates a new instance of KBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KBRepository {
	mock := &KBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
