// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modelconfig "github.com/luoxiaojun1992/data-agent/internal/domain/modelconfig"
	mock "github.com/stretchr/testify/mock"
)

// ModelDefaultRepository is an autogenerated mock type for the ModelDefaultRepository type
type ModelDefaultRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, useCase
func (_m *ModelDefaultRepository) Delete(ctx context.Context, useCase string) error {
	ret := _m.Called(ctx, useCase)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, useCase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, useCase
func (_m *ModelDefaultRepository) Get(ctx context.Context, useCase string) (*modelconfig.ModelDefault, error) {
	ret := _m.Called(ctx, useCase)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *modelconfig.ModelDefault
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelconfig.ModelDefault, error)); ok {
		return rf(ctx, useCase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelconfig.ModelDefault); ok {
		r0 = rf(ctx, useCase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelconfig.ModelDefault)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, useCase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *ModelDefaultRepository) List(ctx context.Context) ([]modelconfig.ModelDefault, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []modelconfig.ModelDefault
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]modelconfig.ModelDefault, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []modelconfig.ModelDefault); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]modelconfig.ModelDefault)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, useCase, modelID
func (_m *ModelDefaultRepository) Set(ctx context.Context, useCase string, modelID string) error {
	ret := _m.Called(ctx, useCase, modelID)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, useCase, modelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelDefaultRepository creates a new instance of ModelDefaultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelDefaultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelDefaultRepository {
	mock := &ModelDefaultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
