// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modelconfig "github.com/luoxiaojun1992/data-agent/internal/domain/modelconfig"
	mock "github.com/stretchr/testify/mock"
)

// ModelConfigRepository is an autogenerated mock type for the ModelConfigRepository type
type ModelConfigRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ModelConfigRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *ModelConfigRepository) Get(ctx context.Context, id string) (*modelconfig.ModelEntry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *modelconfig.ModelEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelconfig.ModelEntry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelconfig.ModelEntry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelconfig.ModelEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, entry
func (_m *ModelConfigRepository) Insert(ctx context.Context, entry modelconfig.ModelEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, modelconfig.ModelEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, t, skip, limit
func (_m *ModelConfigRepository) List(ctx context.Context, t modelconfig.ModelType, skip int64, limit int64) ([]modelconfig.ModelEntry, int64, error) {
	ret := _m.Called(ctx, t, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []modelconfig.ModelEntry
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, modelconfig.ModelType, int64, int64) ([]modelconfig.ModelEntry, int64, error)); ok {
		return rf(ctx, t, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, modelconfig.ModelType, int64, int64) []modelconfig.ModelEntry); ok {
		r0 = rf(ctx, t, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]modelconfig.ModelEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, modelconfig.ModelType, int64, int64) int64); ok {
		r1 = rf(ctx, t, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, modelconfig.ModelType, int64, int64) error); ok {
		r2 = rf(ctx, t, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, entry
func (_m *ModelConfigRepository) Update(ctx context.Context, id string, entry modelconfig.ModelEntry) error {
	ret := _m.Called(ctx, id, entry)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, modelconfig.ModelEntry) error); ok {
		r0 = rf(ctx, id, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelConfigRepository creates a new instance of ModelConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelConfigRepository {
	mock := &ModelConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
