// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// CountUnread provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) CountUnread(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, n
func (_m *NotificationRepository) Create(ctx context.Context, n *model.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListForUser provides a mock function with given fields: ctx, userID, skip, limit
func (_m *NotificationRepository) ListForUser(ctx context.Context, userID string, skip int64, limit int64) ([]*model.Notification, int64, error) {
	ret := _m.Called(ctx, userID, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []*model.Notification
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*model.Notification, int64, error)); ok {
		return rf(ctx, userID, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*model.Notification); ok {
		r0 = rf(ctx, userID, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, userID, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, userID, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) MarkAllRead(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *NotificationRepository) MarkRead(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
