// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/luoxiaojun1992/data-agent/internal/repository"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: ctx, before
func (_m *SessionRepository) Cleanup(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, s
func (_m *SessionRepository) Create(ctx context.Context, s repository.SessionRecord) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SessionRecord) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SessionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *SessionRepository) Get(ctx context.Context, id string) (*repository.SessionRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repository.SessionRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repository.SessionRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.SessionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *SessionRepository) ListByUser(ctx context.Context, userID string) ([]*repository.SessionRecord, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*repository.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*repository.SessionRecord, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*repository.SessionRecord); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.SessionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserPaged provides a mock function with given fields: ctx, userID, skip, limit
func (_m *SessionRepository) ListByUserPaged(ctx context.Context, userID string, skip int64, limit int64) ([]*repository.SessionRecord, int64, error) {
	ret := _m.Called(ctx, userID, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserPaged")
	}

	var r0 []*repository.SessionRecord
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*repository.SessionRecord, int64, error)); ok {
		return rf(ctx, userID, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*repository.SessionRecord); ok {
		r0 = rf(ctx, userID, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.SessionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, userID, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, userID, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListDeleted provides a mock function with given fields: ctx, before, limit
func (_m *SessionRepository) ListDeleted(ctx context.Context, before time.Time, limit int64) ([]*repository.SessionRecord, error) {
	ret := _m.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDeleted")
	}

	var r0 []*repository.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) ([]*repository.SessionRecord, error)); ok {
		return rf(ctx, before, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) []*repository.SessionRecord); ok {
		r0 = rf(ctx, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.SessionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int64) error); ok {
		r1 = rf(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Renew provides a mock function with given fields: ctx, id, newExpiry
func (_m *SessionRepository) Renew(ctx context.Context, id string, newExpiry time.Time) error {
	ret := _m.Called(ctx, id, newExpiry)

	if len(ret) == 0 {
		panic("no return value specified for Renew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, newExpiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: ctx, id
func (_m *SessionRepository) Restore(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRecoveryHours provides a mock function with given fields: ctx, hours
func (_m *SessionRepository) SetRecoveryHours(ctx context.Context, hours int) error {
	ret := _m.Called(ctx, hours)

	if len(ret) == 0 {
		panic("no return value specified for SetRecoveryHours")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, hours)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTitle provides a mock function with given fields: ctx, id, title
func (_m *SessionRepository) SetTitle(ctx context.Context, id string, title string) error {
	ret := _m.Called(ctx, id, title)

	if len(ret) == 0 {
		panic("no return value specified for SetTitle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
