// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SysConfigRepository is an autogenerated mock type for the SysConfigRepository type
type SysConfigRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, namespace, key
func (_m *SysConfigRepository) Delete(ctx context.Context, namespace string, key string) error {
	ret := _m.Called(ctx, namespace, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, namespace, key
func (_m *SysConfigRepository) Get(ctx context.Context, namespace string, key string) (*model.SystemConfig, error) {
	ret := _m.Called(ctx, namespace, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.SystemConfig, error)); ok {
		return rf(ctx, namespace, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.SystemConfig); ok {
		r0 = rf(ctx, namespace, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, namespace
func (_m *SysConfigRepository) GetAll(ctx context.Context, namespace string) ([]model.SystemConfig, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SystemConfig, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SystemConfig); ok {
		r0 = rf(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, namespace, key, value
func (_m *SysConfigRepository) Upsert(ctx context.Context, namespace string, key string, value string) error {
	ret := _m.Called(ctx, namespace, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, namespace, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSysConfigRepository creates a new instance of SysConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSysConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SysConfigRepository {
	mock := &SysConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
