// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	task "github.com/luoxiaojun1992/data-agent/internal/domain/task"
)

// TaskRunRepository is an autogenerated mock type for the TaskRunRepository type
type TaskRunRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *TaskRunRepository) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, r
func (_m *TaskRunRepository) Create(ctx context.Context, r *task.TaskRun) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.TaskRun) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *TaskRunRepository) Get(ctx context.Context, id string) (*task.TaskRun, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *task.TaskRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*task.TaskRun, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *task.TaskRun); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, taskID, skip, limit
func (_m *TaskRunRepository) List(ctx context.Context, taskID string, skip int64, limit int64) ([]*task.TaskRun, int64, error) {
	ret := _m.Called(ctx, taskID, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.TaskRun
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*task.TaskRun, int64, error)); ok {
		return rf(ctx, taskID, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*task.TaskRun); ok {
		r0 = rf(ctx, taskID, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.TaskRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, taskID, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, taskID, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateError provides a mock function with given fields: ctx, id, errMsg
func (_m *TaskRunRepository) UpdateError(ctx context.Context, id string, errMsg string) error {
	ret := _m.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateResult provides a mock function with given fields: ctx, id, result
func (_m *TaskRunRepository) UpdateResult(ctx context.Context, id string, result map[string]interface{}) error {
	ret := _m.Called(ctx, id, result)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *TaskRunRepository) UpdateStatus(ctx context.Context, id string, status task.Status) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, task.Status) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRunRepository creates a new instance of TaskRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRunRepository {
	mock := &TaskRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
