// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	task "github.com/luoxiaojun1992/data-agent/internal/domain/task"

	time "time"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *TaskRepository) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, t
func (_m *TaskRepository) Create(ctx context.Context, t *task.Task) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *TaskRepository) Get(ctx context.Context, id string) (*task.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*task.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *task.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, userID, skip, limit
func (_m *TaskRepository) List(ctx context.Context, userID string, skip int64, limit int64) ([]*task.Task, int64, error) {
	ret := _m.Called(ctx, userID, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*task.Task, int64, error)); ok {
		return rf(ctx, userID, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*task.Task); ok {
		r0 = rf(ctx, userID, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) int64); ok {
		r1 = rf(ctx, userID, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = rf(ctx, userID, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListAll provides a mock function with given fields: ctx, userID
func (_m *TaskRepository) ListAll(ctx context.Context, userID string) ([]*task.Task, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*task.Task, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*task.Task); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastRun provides a mock function with given fields: ctx, id, runAt
func (_m *TaskRepository) UpdateLastRun(ctx context.Context, id string, runAt time.Time) error {
	ret := _m.Called(ctx, id, runAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, runAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListScheduled provides a mock function with given fields: ctx, skip, limit, now
func (_m *TaskRepository) ListScheduled(ctx context.Context, skip int64, limit int64, now time.Time) ([]*task.Task, int64, error) {
	ret := _m.Called(ctx, skip, limit, now)

	if len(ret) == 0 {
		panic("no return value specified for ListScheduled")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) ([]*task.Task, int64, error)); ok {
		return rf(ctx, skip, limit, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) []*task.Task); ok {
		r0 = rf(ctx, skip, limit, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, time.Time) int64); ok {
		r1 = rf(ctx, skip, limit, now)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, time.Time) error); ok {
		r2 = rf(ctx, skip, limit, now)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkScheduledDone provides a mock function with given fields: ctx, id
func (_m *TaskRepository) MarkScheduledDone(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkScheduledDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetScheduledEnabled provides a mock function with given fields: ctx, id, enabled
func (_m *TaskRepository) SetScheduledEnabled(ctx context.Context, id string, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetScheduledEnabled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
