// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/luoxiaojun1992/data-agent/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// VectorRepository is an autogenerated mock type for the VectorRepository type
type VectorRepository struct {
	mock.Mock
}

// DeleteCollection provides a mock function with given fields: ctx, collection
func (_m *VectorRepository) DeleteCollection(ctx context.Context, collection string) error {
	ret := _m.Called(ctx, collection)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, collection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, collection, vector, topK, filter
func (_m *VectorRepository) Search(ctx context.Context, collection string, vector []float32, topK int, filter map[string]interface{}) ([]repository.VectorSearchHit, error) {
	ret := _m.Called(ctx, collection, vector, topK, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []repository.VectorSearchHit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []float32, int, map[string]interface{}) ([]repository.VectorSearchHit, error)); ok {
		return rf(ctx, collection, vector, topK, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []float32, int, map[string]interface{}) []repository.VectorSearchHit); ok {
		r0 = rf(ctx, collection, vector, topK, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.VectorSearchHit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []float32, int, map[string]interface{}) error); ok {
		r1 = rf(ctx, collection, vector, topK, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, collection, vectors
func (_m *VectorRepository) Upsert(ctx context.Context, collection string, vectors []repository.VectorPoint) error {
	ret := _m.Called(ctx, collection, vectors)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []repository.VectorPoint) error); ok {
		r0 = rf(ctx, collection, vectors)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVectorRepository creates a new instance of VectorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVectorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VectorRepository {
	mock := &VectorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
