FROM mcr.microsoft.com/playwright:v1.49.1-jammy

WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN mkdir -p artifacts/allure-results artifacts/coverage

CMD ["npx", "playwright", "test", "-c", "playwright.config.ts"]
