import { test, expect } from '@playwright/test';

const uid = Date.now().toString(36);

/**
 * IM Bind E2E tests.
 *
 * UI-161 & UI-162 test the Web bind page UI. Tokens are normally generated by the
 * Feishu IM service (not available in test env), so we mock at the HTTP layer.
 * UI-163 ~ UI-166 are Feishu client-side features → manual testing only.
 */

test.describe('IM — SPEC-034', () => {
  // ═══ UI-161: 飞书用户绑定页 ═══
  test('[UI-161] IM — 飞书用户绑定页', async ({ page }) => {
    // Mock the token check to return valid
    await page.route('**/api/v1/im/bind/check/**', async (route) => {
      await route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify({ feishu_user_id: 'ou_test_001' }) });
    });
    // Mock confirm to return success
    await page.route('**/api/v1/im/bind/confirm', async (route) => {
      await route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify({ message: '绑定成功' }) });
    });

    await page.goto('/im/bind?token=VALID_TOKEN');
    await page.waitForSelector('[data-testid="im-bind-page"]', { timeout: 10000 });

    // Verify bind page elements
    await expect(page.locator('[data-testid="im-bind-email"]')).toBeVisible();
    await expect(page.locator('[data-testid="im-bind-password"]')).toBeVisible();
    await expect(page.locator('[data-testid="im-bind-submit"]')).toBeVisible();

    // Fill and submit
    await page.locator('[data-testid="im-bind-email"]').fill('user@test.com');
    await page.locator('[data-testid="im-bind-password"]').fill('password');
    await page.locator('[data-testid="im-bind-submit"]').click();

    await expect(page.locator('text=绑定成功')).toBeVisible({ timeout: 5000 });
  });

  // ═══ UI-162: 绑定 Token 过期 ═══
  test('[UI-162] IM — 绑定 Token 过期', async ({ page }) => {
    // Mock check to return expired
    await page.route('**/api/v1/im/bind/check/**', async (route) => {
      await route.fulfill({ status: 410, contentType: 'application/json',
        body: JSON.stringify({ error: '绑定链接已过期' }) });
    });

    await page.goto('/im/bind?token=EXPIRED_TOKEN');
    await page.waitForSelector('[data-testid="im-bind-expired"]', { timeout: 10000 });

    await expect(page.locator('[data-testid="im-bind-expired"]')).toContainText('已过期');
  });

  // ═══ UI-163~166: 飞书客户端功能 → 人工测试 ═══
});
