import { test, expect } from '@playwright/test';

/**
 * IM Bind E2E tests.
 *
 * Tokens are generated by the Feishu IM service and validated by the backend
 * (GET /api/v1/im/bind/check/:token, POST /api/v1/im/bind/confirm).
 *
 * Since there is no real Feishu in the test environment, we mock at the HTTP
 * boundary with the same response format the real backend would return.
 * UI-163 ~ UI-166 are Feishu client-side features → manual testing only.
 */

test.describe('IM — SPEC-034', () => {
  // ═══ UI-161: 飞书用户绑定页 ═══
  test('[UI-161] IM — 飞书用户绑定页', async ({ page }) => {
    // Mock token check (same response as real GET /im/bind/check/:token with valid token)
    await page.route('**/api/v1/im/bind/check/**', async (route) => {
      await route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify({ feishu_user_id: 'ou_test_001' }) });
    });
    // Mock confirm (same response as real POST /im/bind/confirm on success)
    await page.route('**/api/v1/im/bind/confirm', async (route) => {
      await route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify({ message: '绑定成功' }) });
    });

    await page.goto('/im/bind?token=VALID_TOKEN');
    await page.waitForSelector('[data-testid="im-bind-page"]', { timeout: 10000 });

    await expect(page.locator('[data-testid="im-bind-email"]')).toBeVisible();
    await expect(page.locator('[data-testid="im-bind-password"]')).toBeVisible();
    await expect(page.locator('[data-testid="im-bind-submit"]')).toBeVisible();

    await page.locator('[data-testid="im-bind-email"]').fill('user@test.com');
    await page.locator('[data-testid="im-bind-password"]').fill('password');
    await page.locator('[data-testid="im-bind-submit"]').click();

    await expect(page.locator('text=绑定成功')).toBeVisible({ timeout: 5000 });
  });

  // ═══ UI-162: 绑定 Token 过期 ═══
  test('[UI-162] IM — 绑定 Token 过期', async ({ page }) => {
    // Mock check to return 410 Gone — same as real backend when token expired
    await page.route('**/api/v1/im/bind/check/**', async (route) => {
      await route.fulfill({ status: 410, contentType: 'application/json',
        body: JSON.stringify({ error: '绑定链接已过期' }) });
    });

    await page.goto('/im/bind?token=EXPIRED_TOKEN');
    await page.waitForSelector('[data-testid="im-bind-expired"]', { timeout: 10000 });

    await expect(page.locator('[data-testid="im-bind-expired"]')).toContainText('已过期');
  });

  // ═══ UI-163~166: 飞书客户端功能 → 人工测试 ═══
});
