// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/luoxiaojun1992/data-agent/internal/service/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CompleteRegistration provides a mock function with given fields: ctx, req
func (_m *AuthService) CompleteRegistration(ctx context.Context, req *auth.CompleteRegistrationRequest) (*auth.CompleteRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRegistration")
	}

	var r0 *auth.CompleteRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.CompleteRegistrationRequest) (*auth.CompleteRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.CompleteRegistrationRequest) *auth.CompleteRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CompleteRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.CompleteRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateInvite provides a mock function with given fields: ctx, createdBy, req
func (_m *AuthService) CreateInvite(ctx context.Context, createdBy string, req *auth.CreateInviteRequest) (*auth.CreateInviteResponse, error) {
	ret := _m.Called(ctx, createdBy, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 *auth.CreateInviteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.CreateInviteRequest) (*auth.CreateInviteResponse, error)); ok {
		return rf(ctx, createdBy, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.CreateInviteRequest) *auth.CreateInviteResponse); ok {
		r0 = rf(ctx, createdBy, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CreateInviteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *auth.CreateInviteRequest) error); ok {
		r1 = rf(ctx, createdBy, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsInviteEnabled provides a mock function with no fields
func (_m *AuthService) IsInviteEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInviteEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ListInvites provides a mock function with given fields: ctx, createdBy, page, pageSize
func (_m *AuthService) ListInvites(ctx context.Context, createdBy string, page int64, pageSize int64) (*auth.ListInvitesResponse, error) {
	ret := _m.Called(ctx, createdBy, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListInvites")
	}

	var r0 *auth.ListInvitesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) (*auth.ListInvitesResponse, error)); ok {
		return rf(ctx, createdBy, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) *auth.ListInvitesResponse); ok {
		r0 = rf(ctx, createdBy, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ListInvitesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, createdBy, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthService) Login(ctx context.Context, req *auth.LoginRequest) (*auth.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) (*auth.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) *auth.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, userID, username, role
func (_m *AuthService) RefreshToken(ctx context.Context, userID string, username string, role string) (*auth.LoginResponse, error) {
	ret := _m.Called(ctx, userID, username, role)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*auth.LoginResponse, error)); ok {
		return rf(ctx, userID, username, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *auth.LoginResponse); ok {
		r0 = rf(ctx, userID, username, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, username, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req *auth.RegisterRequest) (*auth.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) (*auth.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) *auth.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeInvite provides a mock function with given fields: ctx, inviteID
func (_m *AuthService) RevokeInvite(ctx context.Context, inviteID string) error {
	ret := _m.Called(ctx, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, inviteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateHMACSecret provides a mock function with given fields: ctx, newSecret
func (_m *AuthService) UpdateHMACSecret(ctx context.Context, newSecret string) error {
	ret := _m.Called(ctx, newSecret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHMACSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, newSecret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyInviteToken provides a mock function with given fields: ctx, token
func (_m *AuthService) VerifyInviteToken(ctx context.Context, token string) (*auth.VerifyInviteResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyInviteToken")
	}

	var r0 *auth.VerifyInviteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.VerifyInviteResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.VerifyInviteResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerifyInviteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
