// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	chat "github.com/luoxiaojun1992/data-agent/internal/service/chat"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

// Cleanup provides a mock function with no fields
func (_m *SessionService) Cleanup() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: userID, sessionType
func (_m *SessionService) Create(userID string, sessionType string) (*chat.Session, error) {
	ret := _m.Called(userID, sessionType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *chat.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*chat.Session, error)); ok {
		return rf(userID, sessionType)
	}
	if rf, ok := ret.Get(0).(func(string, string) *chat.Session); ok {
		r0 = rf(userID, sessionType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, sessionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *SessionService) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *SessionService) Get(id string) (*chat.Session, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *chat.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*chat.Session, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *chat.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: userID
func (_m *SessionService) ListByUser(userID string) ([]*chat.Session, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*chat.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*chat.Session, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*chat.Session); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeleted provides a mock function with given fields: before, limit
func (_m *SessionService) ListDeleted(before time.Time, limit int64) ([]*chat.Session, error) {
	ret := _m.Called(before, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDeleted")
	}

	var r0 []*chat.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, int64) ([]*chat.Session, error)); ok {
		return rf(before, limit)
	}
	if rf, ok := ret.Get(0).(func(time.Time, int64) []*chat.Session); ok {
		r0 = rf(before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, int64) error); ok {
		r1 = rf(before, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Renew provides a mock function with given fields: id
func (_m *SessionService) Renew(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Renew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: id
func (_m *SessionService) Restore(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRecoveryHours provides a mock function with given fields: hours
func (_m *SessionService) SetRecoveryHours(hours int) error {
	ret := _m.Called(hours)

	if len(ret) == 0 {
		panic("no return value specified for SetRecoveryHours")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(hours)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionService creates a new instance of SessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionService {
	mock := &SessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
