// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	task "github.com/luoxiaojun1992/data-agent/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// BatchCancelTasks provides a mock function with given fields: ids
func (_m *TaskService) BatchCancelTasks(ids []string) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for BatchCancelTasks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelTask provides a mock function with given fields: id
func (_m *TaskService) CancelTask(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTask provides a mock function with given fields: sessionID, userID, taskType, skillChain, params
func (_m *TaskService) CreateTask(sessionID string, userID string, taskType string, skillChain []string, params map[string]interface{}) (*task.Task, error) {
	ret := _m.Called(sessionID, userID, taskType, skillChain, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, []string, map[string]interface{}) (*task.Task, error)); ok {
		return rf(sessionID, userID, taskType, skillChain, params)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, []string, map[string]interface{}) *task.Task); ok {
		r0 = rf(sessionID, userID, taskType, skillChain, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, []string, map[string]interface{}) error); ok {
		r1 = rf(sessionID, userID, taskType, skillChain, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: id
func (_m *TaskService) GetTask(id string) (*task.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*task.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *task.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllTasks provides a mock function with given fields: userID
func (_m *TaskService) ListAllTasks(userID string) ([]*task.Task, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAllTasks")
	}

	var r0 []*task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*task.Task, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*task.Task); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasks provides a mock function with given fields: userID, status, skip, limit
func (_m *TaskService) ListTasks(userID string, status string, skip int64, limit int64) ([]*task.Task, int64, error) {
	ret := _m.Called(userID, status, skip, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) ([]*task.Task, int64, error)); ok {
		return rf(userID, status, skip, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) []*task.Task); ok {
		r0 = rf(userID, status, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, int64) int64); ok {
		r1 = rf(userID, status, skip, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, int64, int64) error); ok {
		r2 = rf(userID, status, skip, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RetryTask provides a mock function with given fields: id
func (_m *TaskService) RetryTask(id string) (*task.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RetryTask")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*task.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *task.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *TaskService) UpdateStatus(id string, status task.Status) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.Status) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTaskProgress provides a mock function with given fields: id, p
func (_m *TaskService) UpdateTaskProgress(id string, p *task.TaskProgress) error {
	ret := _m.Called(id, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *task.TaskProgress) error); ok {
		r0 = rf(id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTaskResult provides a mock function with given fields: id, result
func (_m *TaskService) UpdateTaskResult(id string, result map[string]interface{}) error {
	ret := _m.Called(id, result)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(id, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
