// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, displayName, permissions
func (_m *Service) Create(ctx context.Context, name string, displayName string, permissions []string) (*model.Role, error) {
	ret := _m.Called(ctx, name, displayName, permissions)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (*model.Role, error)); ok {
		return rf(ctx, name, displayName, permissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) *model.Role); ok {
		r0 = rf(ctx, name, displayName, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, name, displayName, permissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx
func (_m *Service) List(ctx context.Context) ([]model.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPermissions provides a mock function with no fields
func (_m *Service) ListPermissions() []model.PermissionInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []model.PermissionInfo
	if rf, ok := ret.Get(0).(func() []model.PermissionInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PermissionInfo)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, permissions
func (_m *Service) Update(ctx context.Context, id string, permissions []string) error {
	ret := _m.Called(ctx, id, permissions)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, id, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
