// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, namespace, key
func (_m *Service) Delete(ctx context.Context, namespace string, key string) error {
	ret := _m.Called(ctx, namespace, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, namespace
func (_m *Service) GetAll(ctx context.Context, namespace string) ([]model.SystemConfig, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.SystemConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.SystemConfig, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.SystemConfig); ok {
		r0 = rf(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, namespace, page, pageSize
func (_m *Service) List(ctx context.Context, namespace string, page int, pageSize int) ([]model.SystemConfig, int64, error) {
	ret := _m.Called(ctx, namespace, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.SystemConfig
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]model.SystemConfig, int64, error)); ok {
		return rf(ctx, namespace, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []model.SystemConfig); ok {
		r0 = rf(ctx, namespace, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SystemConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, namespace, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, namespace, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SeedBuiltins provides a mock function with given fields: ctx
func (_m *Service) SeedBuiltins(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SeedBuiltins")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, namespace, key, value
func (_m *Service) Upsert(ctx context.Context, namespace string, key string, value string) error {
	ret := _m.Called(ctx, namespace, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, namespace, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
