// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/luoxiaojun1992/data-agent/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: title, content, nType
func (_m *NotificationService) Broadcast(title string, content string, nType string) (*model.Notification, error) {
	ret := _m.Called(title, content, nType)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 *model.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*model.Notification, error)); ok {
		return rf(title, content, nType)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *model.Notification); ok {
		r0 = rf(title, content, nType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(title, content, nType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListForUser provides a mock function with given fields: userID, limit
func (_m *NotificationService) ListForUser(userID string, limit int64) ([]model.Notification, error) {
	ret := _m.Called(userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []model.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64) ([]model.Notification, error)); ok {
		return rf(userID, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int64) []model.Notification); ok {
		r0 = rf(userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAllRead provides a mock function with given fields: userID
func (_m *NotificationService) MarkAllRead(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkRead provides a mock function with given fields: id, userID
func (_m *NotificationService) MarkRead(id string, userID string) error {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: title, content, nType, targetIDs
func (_m *NotificationService) Send(title string, content string, nType string, targetIDs []string) (*model.Notification, error) {
	ret := _m.Called(title, content, nType, targetIDs)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *model.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, []string) (*model.Notification, error)); ok {
		return rf(title, content, nType, targetIDs)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, []string) *model.Notification); ok {
		r0 = rf(title, content, nType, targetIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, []string) error); ok {
		r1 = rf(title, content, nType, targetIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnreadCount provides a mock function with given fields: userID
func (_m *NotificationService) UnreadCount(userID string) (int64, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
