// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "net/http"

	im "github.com/luoxiaojun1992/data-agent/internal/service/im"
	mock "github.com/stretchr/testify/mock"
)

// IMService is an autogenerated mock type for the IMService type
type IMService struct {
	mock.Mock
}

// FormatCard provides a mock function with given fields: card
func (_m *IMService) FormatCard(card im.CardMessage) map[string]interface{} {
	ret := _m.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for FormatCard")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(im.CardMessage) map[string]interface{}); ok {
		r0 = rf(card)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// FormatTextMessage provides a mock function with given fields: text
func (_m *IMService) FormatTextMessage(text string) map[string]interface{} {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for FormatTextMessage")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// VerifySignature provides a mock function with given fields: timestamp, nonce, sign
func (_m *IMService) VerifySignature(timestamp string, nonce string, sign string) bool {
	ret := _m.Called(timestamp, nonce, sign)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(timestamp, nonce, sign)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WebhookHandler provides a mock function with no fields
func (_m *IMService) WebhookHandler() http.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebhookHandler")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewIMService creates a new instance of IMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMService {
	mock := &IMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
